# This file was generated by GoReleaser. DO NOT EDIT.
class NightWatch < Formula
  desc "night-watch"
  homepage "https://dashbase.io/"
  url "https://github.com/dashbase/night-watch/releases/download/v1.1.0-rc1/night-watch_1.1.0-rc1_macOS_64-bit.tar.gz"
  version "1.1.0-rc1"
  sha256 "6ef33596d209f005d19349f4e852715aea6c815797ceb39e5137016214c98820"

  def install
    bin.install "night-watch"
  end

  test do
    system "#{bin}/night-watch version"
  end
end
